
set(EXTERNAL_LIB_DIR "${CMAKE_SOURCE_DIR}/external")

set(GLUT_ROOT "${EXTERNAL_LIB_DIR}/freeglut-2.6.0")
set(GLM_ROOT "${EXTERNAL_LIB_DIR}/glm-0.9.0.7")
set(LIB3DS_ROOT "${EXTERNAL_LIB_DIR}/lib3ds-2.0")
set(DEVIL_ROOT "${EXTERNAL_LIB_DIR}/DevIL-1.7.3")