
set(EXTERNAL_LIB_DIR "${CMAKE_SOURCE_DIR}/external")

set(GLUT_ROOT "${EXTERNAL_LIB_DIR}/freeglut-2.8.1")
set(GLM_ROOT "${EXTERNAL_LIB_DIR}/glm-0.9.4.3")
set(DEVIL_ROOT "${EXTERNAL_LIB_DIR}/DevIL-1.7.8")